### ISSUE TITLE
Bug: schema typescript command failing

### ISSUE THREAD

**Issue by Kumzy** [litestar-org/litestar-fullstack#105]
### Description

On clear pull of the repo and after running `make install`. Trying to run `app schema typescript` results in an error
The error displayed do not give me enough information to find the root issue

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Pull main branch
2. Install using `make install`
3. Activate venv
4. Run `app schema typescript` command
5. See error
```

### Screenshots

"In the format of: `![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)`"

### Logs

```bash
Traceback (most recent call last):
  File "/project/litestar-fullstack/.venv/bin/app", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/project/litestar-fullstack/src/app/__main__.py", line 23, in run_cli
    run_litestar_cli()
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/__main__.py", line 6, in run_cli
    litestar_group()
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/cli/_utils.py", line 280, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/cli/_utils.py", line 280, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/cli/commands/schema.py", line 81, in generate_typescript_specs
    specs = convert_openapi_to_typescript(app.openapi_schema, namespace)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/_openapi/typescript_converter/converter.py", line 291, in convert_openapi_to_typescript
    parse_request_body(
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/_openapi/typescript_converter/converter.py", line 205, in parse_request_body
    parse_schema(schema) if body.required else TypeScriptUnion((parse_schema(schema), undefined)),
    ^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/_openapi/typescript_converter/schema_parsing.py", line 152, in parse_schema
    return parse_type_schema(schema=schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/litestar-fullstack/.venv/lib/python3.12/site-packages/litestar/_openapi/typescript_converter/schema_parsing.py", line 129, in parse_type_schema
    raise TypeError(f"received an unexpected openapi type: {schema.type}")  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: received an unexpected openapi type: None
```

### Package Version

Main branch of litestar-fullstack

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
The `TagUpdateDTO` wasn't configured for that handler, and so combined with the `DTOData` annotation, the schema type was being set to `None`. This change to the source fixed it:

```diff
diff --git a/src/app/domain/tags/controllers.py b/src/app/domain/tags/controllers.py
index 4718638..61e2886 100644
--- a/src/app/domain/tags/controllers.py
+++ b/src/app/domain/tags/controllers.py
@@ -9,7 +9,7 @@ from litestar.params import Dependency, Parameter
 from app.domain import urls
 from app.domain.accounts.guards import requires_active_user, requires_superuser
 from app.domain.tags.dependencies import provide_tags_service
-from app.domain.tags.dtos import TagCreateDTO, TagDTO
+from app.domain.tags.dtos import TagCreateDTO, TagUpdateDTO, TagDTO
 from app.lib import log
 
 if TYPE_CHECKING:
@@ -95,6 +95,7 @@ class TagController(Controller):
         name="tags:update",
         path=urls.TAG_UPDATE,
         guards=[requires_superuser],
+        dto=TagUpdateDTO,
     )
     async def update_tag(
         self,
```

We should probably do something in litestar to make this type of error more explicit on startup, i.e., a `DTOData` annotation without a configured DTO for the route should be a configuration error.

**Comment by Kumzy** [comment]
I was using litestar 2.3.2  that the repo use. This fix the issue
